### PR TITLE
feat: renaming subcommand "/create custom" to "/create activity", fixing comments (closes #17)

### LINKED ISSUE #17: Rename command `/create custom` to `/create activity`
Current name of subCommand is confusing.

### PR DESCRIPTION
**Pull request by EncyOnCode**
Renamed subcommand 'create custom' to 'create activity' so it's not confusing anymore. Also fixed the comments to match the actual commands.

### CODE REVIEW

File: lib/core/data/enums/activity_type.dart [hunk 1]
```diff
@@ -9,12 +9,12 @@ enum LFGActivityType {
...
   ///
-  /// All custom activities registers in `/create custom` command.
-  custom,
+  /// All custom activities registers in `/create activity` command.
+  activity,
 
   /// Dungeon activity, stored in `/activities/dungeons.json` file.
   ///
-  /// Main difference from [LFGActivityType.custom] is that it has fixed number of members: 3.
+  /// Main difference from [LFGActivityType.activity] is that it has fixed number of members: 3.
```
Comment (Tembeon) [inline lib/core/data/enums/activity_type.dart]: I think enum name `LFGActivityType.activity` sounds odd. Maybe rename `LFGActivityType` to `LFGType`?

**Review by Tembeon — APPROVED** [review]
LGTM
